// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/tasks/service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/avraam311/tasks-service/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// DeleteTask mocks base method.
func (m *MockRepo) DeleteTask(ctx context.Context, taskID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockRepoMockRecorder) DeleteTask(ctx, taskID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockRepo)(nil).DeleteTask), ctx, taskID)
}

// LoadAllTasks mocks base method.
func (m *MockRepo) LoadAllTasks(ctx context.Context) ([]*models.TaskDomain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadAllTasks", ctx)
	ret0, _ := ret[0].([]*models.TaskDomain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadAllTasks indicates an expected call of LoadAllTasks.
func (mr *MockRepoMockRecorder) LoadAllTasks(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadAllTasks", reflect.TypeOf((*MockRepo)(nil).LoadAllTasks), ctx)
}

// LoadTask mocks base method.
func (m *MockRepo) LoadTask(ctx context.Context, taskID uint) (*models.TaskDomain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadTask", ctx, taskID)
	ret0, _ := ret[0].(*models.TaskDomain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadTask indicates an expected call of LoadTask.
func (mr *MockRepoMockRecorder) LoadTask(ctx, taskID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadTask", reflect.TypeOf((*MockRepo)(nil).LoadTask), ctx, taskID)
}

// StoreTask mocks base method.
func (m *MockRepo) StoreTask(ctx context.Context, task *models.TaskDTO) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreTask", ctx, task)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreTask indicates an expected call of StoreTask.
func (mr *MockRepoMockRecorder) StoreTask(ctx, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreTask", reflect.TypeOf((*MockRepo)(nil).StoreTask), ctx, task)
}

// SwapTask mocks base method.
func (m *MockRepo) SwapTask(ctx context.Context, taskID uint, task *models.TaskDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwapTask", ctx, taskID, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// SwapTask indicates an expected call of SwapTask.
func (mr *MockRepoMockRecorder) SwapTask(ctx, taskID, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwapTask", reflect.TypeOf((*MockRepo)(nil).SwapTask), ctx, taskID, task)
}
